### ISSUE TITLE
IB+CB Loss

### ISSUE THREAD

**Issue by Never-Walk-Away** [pseulki/IB-Loss#2]
Thank you very much for your excellent work. Excuse me, is the combination of IB loss and CB loss multiplied by IB weighting factor on the basis of CB loss。that is I want to know the mathematical expression of CB + IB loss.
I look forward to your reply！

**Comment by pseulki** [comment]
Hello, I'm sorry for the late reply.
You are right! 
In equation (6), $L(y,f(x,w))$ is replaced by CB loss, as can be seen in code too.
If you have any further question, please ask me!
Thank you for your interest!

**Comment by Never-Walk-Away** [comment]
thanks!
